const express = require('express');
const cors = require('cors');
const cookieParser = require('cookie-parser');
const authRoutes = require('./routes/auth');
const transactionRoutes = require('./routes/transactions');
const { apiError, errorHandler } = require('./middlewares/errors');
const app = express();
app.disable('x-powered-by');
app.use(cors({ origin: process.env.CORS_ORIGIN || 'http://127.0.0.1:3000', credentials: true }));
app.use(express.json({ limit: '16kb' }));
app.use(cookieParser());
app.get('/', (req, res) => res.json({ message: 'Expense Diary API is running' }));
app.use('/auth', authRoutes);
app.use('/transactions', transactionRoutes);
app.use((req, res, next) => next(apiError(404, 'Route not found')));
app.use(errorHandler);
module.exports = app;
